// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oudmxovaphajgyshwlck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91ZG14b3ZhcGhhamd5c2h3bGNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTYwODUsImV4cCI6MjA2NjY3MjA4NX0.ZqaaFG-XpRobtaePDZn8g99CcinBt86HfwyJI5yLZNQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});